#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Base de données complète de tous les outils système
548+ outils organisés en 12 sections
Extrait de NiTriTe V12
"""

def get_all_tools():
    """Retourne tous les outils organisés par section"""
    return {
        "🔨 Réparation Système": [
            ("🔍 DISM Check", "DISM /Online /Cleanup-Image /CheckHealth"),
            ("🔎 DISM Scan", "DISM /Online /Cleanup-Image /ScanHealth"),
            ("🔧 DISM Restore", "DISM /Online /Cleanup-Image /RestoreHealth"),
            ("🛠️ SFC Scan", "sfc /scannow"),
            ("💽 CHKDSK C:", "chkdsk C: /f /r"),
            ("💾 CHKDSK D:", "chkdsk D: /f /r"),
            ("🔄 Reset WinSock", "netsh winsock reset"),
            ("🌐 Reset TCP/IP", "netsh int ip reset"),
            ("🔧 Reset Firewall", "netsh advfirewall reset"),
            ("📡 Reset Proxy", "netsh winhttp reset proxy"),
            ("🔄 Reset DNS", "ipconfig /flushdns"),
            ("🔌 Reset Network", "netsh int ip reset && netsh winsock reset"),
            ("🛠️ Repair BCD", "bcdedit /export C:\\BCD_Backup & attrib c:\\boot\\bcd -h -r -s & ren c:\\boot\\bcd bcd.old & bootrec /rebuildbcd"),
            ("💿 Repair Boot", "bootrec /fixmbr && bootrec /fixboot && bootrec /rebuildbcd"),
            ("🔧 System Reset", "systemreset"),
            ("🔄 Windows Update Reset", "net stop wuauserv && net stop cryptSvc && net stop bits && net stop msiserver && ren C:\\Windows\\SoftwareDistribution SoftwareDistribution.old && ren C:\\Windows\\System32\\catroot2 catroot2.old && net start wuauserv && net start cryptSvc && net start bits && net start msiserver"),
            ("📦 Repair Store", "wsreset"),
            ("🛡️ Windows Defender Repair", "cd %ProgramFiles%\\Windows Defender && MpCmdRun.exe -removedefinitions -dynamicsignatures && MpCmdRun.exe -SignatureUpdate"),
            ("🔧 DISM Mount Cleanup", "DISM /Cleanup-Mountpoints"),
            ("💾 Check Disk Bad Sectors", "chkdsk /r /f"),
            ("🔍 Verify System Files", "sfc /verifyonly"),
            ("📋 Export DISM Log", "DISM /Online /Cleanup-Image /RestoreHealth /LogPath:C:\\DISM_RestoreHealth.log"),
            ("🔧 Repair Windows Image", "DISM /Online /Cleanup-Image /RestoreHealth /Source:WIM:X:\\sources\\install.wim:1 /LimitAccess"),
            ("🛠️ System File Check Extended", "sfc /scannow /offbootdir=C:\\ /offwindir=C:\\Windows"),
            ("🔄 Reset Windows Activation", "slmgr /rearm"),
            ("📡 Reset Network Adapter", "netsh interface set interface \"Ethernet\" admin=disable && netsh interface set interface \"Ethernet\" admin=enable"),
            ("🔌 Reset Wi-Fi", "netsh interface set interface \"Wi-Fi\" admin=disable && netsh interface set interface \"Wi-Fi\" admin=enable"),
            ("🔧 Rebuild Icon Cache", "ie4uinit.exe -show && ie4uinit.exe -ClearIconCache"),
            ("🗂️ Rebuild Search Index", "net stop WSearch && del /f /s /q %ProgramData%\\Microsoft\\Search\\Data\\Applications\\Windows\\Windows.edb && net start WSearch"),
            ("📝 Repair Start Menu", "Get-AppXPackage -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register \"$($_.InstallLocation)\\AppXManifest.xml\"}"),
            ("🔄 Reset Windows Store", "wsreset && powershell -ExecutionPolicy Unrestricted Add-AppxPackage -DisableDevelopmentMode -Register $Env:SystemRoot\\WinStore\\AppxManifest.xml"),
        ],

        "🔧 Activation & Téléchargements": [
            ("⚡ PowerToys", "https://github.com/microsoft/PowerToys/releases/latest"),
            ("📦 Office FR", "https://gravesoft.dev/office_c2r_links#french-fr-france"),
            ("📋 Office EN", "https://gravesoft.dev/office_c2r_links"),
            ("🔑 MS Activation Scripts", "https://massgrave.dev/"),
            ("🎯 Activation Scripts", "https://get.activated.win"),
            ("💿 Windows ISO", "https://www.microsoft.com/software-download/windows10"),
            ("💾 Windows 11 ISO", "https://www.microsoft.com/software-download/windows11"),
            ("📀 Media Creation Tool", "https://www.microsoft.com/software-download/windows10"),
            ("🔥 Rufus", "https://rufus.ie/"),
            ("💽 Ventoy", "https://www.ventoy.net/"),
            ("🔧 WinToUSB", "https://www.easyuefi.com/wintousb/"),
            ("💿 Etcher", "https://www.balena.io/etcher/"),
            ("📦 Ninite", "https://ninite.com/"),
            ("🔄 Patch My PC", "https://patchmypc.com/home-updater"),
            ("🛠️ Windows Toolkit", "https://github.com/ChrisTitusTech/winutil"),
            ("🔑 KMS Tools", "https://www.ratiborus.com/"),
            ("⚡ AutoKMS", "https://github.com/massgravel/Microsoft-Activation-Scripts"),
            ("📋 Office Tool Plus", "https://otp.landian.vip/"),
            ("🔧 Windows Repair Toolbox", "https://windows-repair-toolbox.com/"),
            ("🛡️ Windows Update Blocker", "https://www.sordum.org/9470/"),
            ("🔄 Windows Update Reset Script", "https://wureset.com/"),
            ("💻 Sysinternals Suite", "https://docs.microsoft.com/sysinternals/downloads/sysinternals-suite"),
            ("🔧 Ultimate Windows Tweaker", "https://www.thewindowsclub.com/ultimate-windows-tweaker-4-windows-10"),
            ("⚙️ O&O ShutUp10++", "https://www.oo-software.com/en/shutup10"),
            ("🛠️ Winaero Tweaker", "https://winaerotweaker.com/"),
            ("🎨 Rainmeter", "https://www.rainmeter.net/"),
            ("🖥️ DisplayFusion", "https://www.displayfusion.com/"),
            ("📊 HWiNFO", "https://www.hwinfo.com/"),
            ("🔍 Speccy", "https://www.ccleaner.com/speccy"),
        ],

        "🧹 Maintenance & Nettoyage": [
            ("🧹 Disk Cleanup", "cleanmgr"),
            ("📦 Cleanup Full", "cleanmgr /sageset:1 & cleanmgr /sagerun:1"),
            ("🗂️ Clean WinSxS", "DISM /Online /Cleanup-Image /StartComponentCleanup"),
            ("🔧 WinSxS Analyze", "DISM /Online /Cleanup-Image /AnalyzeComponentStore"),
            ("💾 WinSxS Deep Clean", "DISM /Online /Cleanup-Image /StartComponentCleanup /ResetBase"),
            ("🗑️ Temp Cleanup", "del /q/f/s %TEMP%\\*"),
            ("📁 Delete Prefetch", "del /q/f/s C:\\Windows\\Prefetch\\*"),
            ("🔄 Empty Recycle Bin", "rd /s /q C:\\$Recycle.bin"),
            ("💿 Clean Update Cache", "dism /online /Cleanup-Image /StartComponentCleanup /ResetBase"),
            ("🧹 CCleaner", "https://www.ccleaner.com/ccleaner/download"),
            ("🗑️ BleachBit", "https://www.bleachbit.org/"),
            ("🔧 Wise Disk Cleaner", "https://www.wisecleaner.com/wise-disk-cleaner.html"),
            ("📦 Glary Utilities", "https://www.glarysoft.com/"),
            ("🧽 Privazer", "https://privazer.com/"),
            ("🔧 CleanMyPC", "https://macpaw.com/cleanmypc"),
        ],

        "📊 Diagnostics & Infos": [
            ("💻 System Info", "msinfo32"),
            ("🎮 DirectX Diag", "dxdiag"),
            ("📊 Event Viewer", "eventvwr.msc"),
            ("🔧 Device Manager", "devmgmt.msc"),
            ("⚙️ Task Manager", "taskmgr"),
            ("📈 Resource Monitor", "resmon"),
            ("💾 Disk Management", "diskmgmt.msc"),
            ("🖥️ Computer Management", "compmgmt.msc"),
            ("📋 Services", "services.msc"),
            ("⚡ Performance Monitor", "perfmon"),
            ("🔍 Reliability Monitor", "perfmon /rel"),
            ("💿 Disk Defrag", "dfrgui"),
            ("🔧 Registry Editor", "regedit"),
            ("📝 Group Policy", "gpidit.msc"),
            ("🔐 Local Security Policy", "secpol.msc"),
            ("👥 User Accounts", "netplwiz"),
            ("🖨️ Print Management", "printmanagement.msc"),
            ("🌐 Component Services", "dcomcnfg"),
            ("📦 Programs and Features", "appwiz.cpl"),
            ("🔧 Advanced System Properties", "systempropertiesadvanced"),
            ("🖥️ Display Settings", "desk.cpl"),
            ("🔊 Sound Settings", "mmsys.cpl"),
            ("🎮 Game Controllers", "joy.cpl"),
            ("🖱️ Mouse Settings", "main.cpl"),
            ("⌨️ Keyboard Settings", "control keyboard"),
            ("🌍 Region Settings", "intl.cpl"),
            ("⏰ Date and Time", "timedate.cpl"),
            ("🔋 Power Options", "powercfg.cpl"),
            ("🛡️ Windows Security", "windowsdefender:"),
            ("🔄 Windows Update", "ms-settings:windowsupdate"),
            ("📱 Phone Settings", "ms-settings:mobile-devices"),
            ("🔗 Connected Devices", "ms-settings:connecteddevices"),
            ("🎨 Personalization", "ms-settings:personalization"),
            ("🔊 Sound Panel", "ms-settings:sound"),
            ("🌐 Network Status", "ms-settings:network-status"),
            ("📶 Wi-Fi Settings", "ms-settings:network-wifi"),
            ("🔌 Ethernet", "ms-settings:network-ethernet"),
            ("📡 VPN", "ms-settings:network-vpn"),
            ("🌍 Proxy", "ms-settings:network-proxy"),
            ("💾 Storage", "ms-settings:storagesense"),
            ("🔋 Battery", "ms-settings:batterysaver"),
            ("⚡ Battery Usage", "ms-settings:batterysaver-usagedetails"),
            ("🖥️ Display", "ms-settings:display"),
            ("📺 Night Light", "ms-settings:nightlight"),
            ("🎮 Gaming", "ms-settings:gaming"),
            ("🎯 Game Mode", "ms-settings:gaming-gamemode"),
            ("📹 Game Bar", "ms-settings:gaming-gamebar"),
            ("🔇 Audio Mixer", "sndvol"),
            ("🔊 Volume Mixer", "sndvol"),
            ("🖥️ Screen Resolution", "ms-settings:display"),
            ("🎨 Background", "ms-settings:personalization-background"),
            ("🔒 Lock Screen", "ms-settings:lockscreen"),
            ("🎨 Colors", "ms-settings:colors"),
            ("🖱️ Mouse & Cursor", "ms-settings:mousetouchpad"),
            ("⌨️ Typing", "ms-settings:typing"),
        ],

        "🌐 Réseau & Internet": [
            ("🌐 Ping Google", "ping 8.8.8.8 -n 10"),
            ("🔍 NSLookup", "nslookup google.com"),
            ("📡 IPConfig", "ipconfig /all"),
            ("🔄 Release IP", "ipconfig /release"),
            ("🔌 Renew IP", "ipconfig /renew"),
            ("🗑️ Flush DNS", "ipconfig /flushdns"),
            ("📋 Display DNS", "ipconfig /displaydns"),
            ("🔧 Route Print", "route print"),
            ("🌍 Tracert Google", "tracert google.com"),
            ("📡 PathPing", "pathping google.com"),
            ("🔍 NetStat", "netstat -ano"),
            ("📊 NetStat Active", "netstat -a"),
            ("🔧 NetStat Routes", "netstat -r"),
            ("🌐 ARP Table", "arp -a"),
            ("🔌 Network Connections", "ncpa.cpl"),
            ("📡 Network Reset", "netsh winsock reset && netsh int ip reset"),
            ("🔧 Reset TCP/IP Stack", "netsh int ip reset"),
            ("🌍 Test Connection", "ping 1.1.1.1 -t"),
            ("📊 Bandwidth Test", "https://www.speedtest.net/"),
            ("🔍 IP Info", "https://www.whatismyip.com/"),
            ("🌐 DNS Benchmark", "https://www.grc.com/dns/benchmark.htm"),
            ("🔧 Port Checker", "https://www.yougetsignal.com/tools/open-ports/"),
        ],

        "⚡ WinGet Package Manager": [
            ("🔄 Upgrade All", "winget upgrade --all"),
            ("📋 List Upgrades", "winget upgrade"),
            ("🔍 Search", "winget search"),
            ("📦 List Installed", "winget list"),
            ("ℹ️ Show Info", "winget show"),
            ("🔧 Install App", "winget install"),
            ("🗑️ Uninstall App", "winget uninstall"),
            ("📋 Export List", "winget export -o C:\\winget-export.json"),
            ("📥 Import List", "winget import -i C:\\winget-export.json"),
            ("🔄 Update WinGet", "winget upgrade Microsoft.Winget.Source"),
            ("📚 WinGet Help", "winget --help"),
            ("⚙️ WinGet Settings", "winget settings"),
        ],

        "⚙️ Paramètres Windows": [
            ("⚙️ Settings", "start ms-settings:"),
            ("🖥️ Display", "start ms-settings:display"),
            ("🔊 Sound", "start ms-settings:sound"),
            ("🔔 Notifications", "start ms-settings:notifications"),
            ("⚡ Power & Sleep", "start ms-settings:powersleep"),
            ("💾 Storage", "start ms-settings:storagesense"),
            ("🌐 Network & Internet", "start ms-settings:network"),
            ("🎨 Personalization", "start ms-settings:personalization"),
            ("📱 Phone", "start ms-settings:mobile-devices"),
            ("👥 Accounts", "start ms-settings:yourinfo"),
            ("⏰ Time & Language", "start ms-settings:dateandtime"),
            ("🎮 Gaming", "start ms-settings:gaming"),
            ("🔐 Privacy", "start ms-settings:privacy"),
            ("🔄 Update & Security", "start ms-settings:windowsupdate"),
            ("♿ Ease of Access", "start ms-settings:easeofaccess"),
            ("🔍 Search", "start ms-settings:search"),
            ("🗣️ Cortana", "start ms-settings:cortana"),
            ("🔗 Apps & Features", "start ms-settings:appsfeatures"),
            ("🏢 For Developers", "start ms-settings:developers"),
        ],

        "🏭 Support Fabricants": [
            ("💻 Dell Support", "https://www.dell.com/support/"),
            ("🖥️ HP Support", "https://support.hp.com/"),
            ("💼 Lenovo Support", "https://support.lenovo.com/"),
            ("⚡ ASUS Support", "https://www.asus.com/support/"),
            ("🔷 Acer Support", "https://www.acer.com/support/"),
            ("📱 MSI Support", "https://www.msi.com/support"),
            ("🖥️ Samsung Support", "https://www.samsung.com/support/"),
            ("💻 Toshiba Support", "https://support.dynabook.com/"),
            ("🔧 Gigabyte Support", "https://www.gigabyte.com/Support"),
            ("⚡ ASRock Support", "https://www.asrock.com/support/"),
            ("🖥️ Intel Support", "https://www.intel.com/content/www/us/en/support.html"),
            ("🎮 AMD Support", "https://www.amd.com/en/support"),
            ("🎨 NVIDIA Support", "https://www.nvidia.com/support/"),
            ("💾 Western Digital Support", "https://support.wdc.com/"),
            ("💿 Seagate Support", "https://www.seagate.com/support/"),
            ("⚡ Corsair Support", "https://www.corsair.com/support"),
            ("🖱️ Logitech Support", "https://support.logi.com/"),
            ("⌨️ Razer Support", "https://support.razer.com/"),
        ],

        "🛒 Fournisseurs & Achats": [
            ("🔧 1fo Trade", "https://www.1fotrade.com/"),
            ("💻 Acadia Info", "https://www.acadia-info.com/"),
            ("📦 Flexit", "https://shop.flexitdistribution.com/"),
            ("💰 1fo Discount", "https://www.1fodiscount.com/"),
            ("📦 Noriak Distri", "https://www.noriak-distri.com/"),
            ("🛒 Amazon FR", "https://www.amazon.fr/"),
            ("🏪 Cdiscount", "https://www.cdiscount.com/"),
            ("🌐 eBay FR", "https://www.ebay.fr/"),
            ("📢 Leboncoin", "https://www.leboncoin.fr/"),
            ("📚 Fnac", "https://www.fnac.com/"),
            ("🔌 Darty", "https://www.darty.com/"),
            ("🏪 Boulanger", "https://www.boulanger.com/"),
            ("🛒 E.Leclerc", "https://www.e.leclerc/"),
            ("🏬 Rue Commerce", "https://www.rueducommerce.fr/"),
            ("🎌 Rakuten", "https://fr.shopping.rakuten.com/"),
            ("🔝 TopAchat", "https://www.topachat.com/"),
            ("💻 Grosbill", "https://www.grosbill.com/"),
            ("💼 Inmac Wstore", "https://www.inmac-wstore.com/"),
            ("🖥️ Visiodirect", "https://www.visiodirect.net/"),
            ("🔧 LDLC", "https://www.ldlc.com/"),
            ("💻 Materiel.net", "https://www.materiel.net/"),
            ("🎮 PC21", "https://www.pc21.fr/"),
            ("💼 Cybertek", "https://www.cybertek.fr/"),
            ("🎯 Config-Gamer", "https://www.config-gamer.fr/"),
            ("💡 Idealo", "https://www.idealo.fr/"),
            ("🔥 Dealabs", "https://www.dealabs.com/"),
            ("🔍 Le Dénicheur", "https://ledenicheur.fr/"),
            ("🍎 OKA Mac", "https://www.okamac.com/fr/"),
            ("🍎 MacWay", "https://www.macway.com/"),
            ("🇨🇭 Digitec CH", "https://www.digitec.ch/fr"),
            ("🌍 Amazon DE", "https://www.amazon.de/"),
            ("🌐 Amazon UK", "https://www.amazon.co.uk/"),
            ("🇺🇸 Amazon US", "https://www.amazon.com/"),
            ("🇺🇸 Newegg", "https://www.newegg.com/"),
            ("📷 B&H Photo", "https://www.bhphotovideo.com/"),
            ("♻️ BackMarket", "https://www.backmarket.fr/"),
            ("🔄 Refurbed", "https://www.refurbed.fr/"),
            ("📦 2ememain.be", "https://www.2ememain.be/"),
            ("🛒 AliExpress", "https://www.aliexpress.com/"),
            ("💰 Wish", "https://www.wish.com/"),
            ("📦 Banggood", "https://www.banggood.com/"),
            ("💾 Crucial FR", "https://www.crucial.fr/"),
            ("💼 Dell FR", "https://www.dell.com/fr-fr"),
            ("🖨️ HP FR", "https://www.hp.com/fr-fr/shop/"),
            ("💻 Lenovo FR", "https://www.lenovo.com/fr/fr/"),
            ("📱 Samsung FR", "https://www.samsung.com/fr/"),
            ("🚗 La Centrale", "https://www.lacentrale.fr/"),
            ("🔒 ProtonVPN", "https://protonvpn.com/"),
            ("🛡️ NordVPN", "https://nordvpn.com/"),
            ("⚡ ExpressVPN", "https://www.expressvpn.com/"),
            ("🔐 Surfshark", "https://surfshark.com/"),
            ("🔒 PIA VPN", "https://www.privateinternetaccess.com/"),
            ("🌐 Mullvad VPN", "https://mullvad.net/"),
            ("🔐 CyberGhost", "https://www.cyberghostvpn.com/"),
            ("⚡ Windscribe", "https://windscribe.com/"),
            ("🔐 Malwarebytes", "https://www.malwarebytes.com/"),
            ("🛡️ Kaspersky", "https://www.kaspersky.fr/"),
            ("🔒 Bitdefender", "https://www.bitdefender.com/"),
            ("⚡ Avast Free", "https://www.avast.com/free-antivirus-download"),
            ("🔐 AVG Free", "https://www.avg.com/free-antivirus-download"),
            ("🛡️ Windows Defender", "windowsdefender:"),
            ("🔒 ESET NOD32", "https://www.eset.com/"),
            ("⚡ Sophos Home", "https://home.sophos.com/"),
            ("🔐 Bitwarden", "https://bitwarden.com/download/"),
            ("🛡️ KeePass", "https://keepass.info/download.html"),
            ("🔒 1Password", "https://1password.com/"),
            ("⚡ LastPass", "https://www.lastpass.com/"),
            ("🔐 Dashlane", "https://www.dashlane.com/"),
            ("🛡️ RoboForm", "https://www.roboform.com/"),
            ("🔒 Keeper", "https://www.keepersecurity.com/"),
            ("⚡ NordPass", "https://nordpass.com/"),
            ("🔐 Authy", "https://authy.com/"),
            ("🛡️ Google Auth", "https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2"),
            ("🔒 MS Authenticator", "https://www.microsoft.com/security/mobile-authenticator-app"),
            ("🔐 Signal Desktop", "https://signal.org/download/"),
            ("🛡️ Threema", "https://threema.ch/"),
            ("🔒 Telegram", "https://telegram.org/"),
            ("⚡ ProtonMail", "https://proton.me/mail"),
            ("🌐 Have I Been Pwned", "https://haveibeenpwned.com/"),
            ("🔐 VirusTotal", "https://www.virustotal.com/"),
            ("🛡️ Hybrid Analysis", "https://www.hybrid-analysis.com/"),
            ("🔒 Any.Run", "https://any.run/"),
            ("⚡ URLScan.io", "https://urlscan.io/"),
            ("🔐 Shodan", "https://www.shodan.io/"),
            ("🛡️ Joe Sandbox", "https://www.joesandbox.com/"),
            ("🔒 Tails OS", "https://tails.boum.org/"),
            ("🛡️ Whonix", "https://www.whonix.org/"),
            ("⚡ Qubes OS", "https://www.qubes-os.org/"),
            ("🔐 Pi-hole", "https://pi-hole.net/"),
            ("🛡️ AdGuard DNS", "https://adguard-dns.io/"),
            ("🔒 uBlock Origin", "https://ublockorigin.com/"),
            ("⚡ Privacy Badger", "https://privacybadger.org/"),
            ("🔐 VeraCrypt", "https://www.veracrypt.fr/"),
            ("🛡️ Cryptomator", "https://cryptomator.org/"),
            ("🔒 AxCrypt", "https://www.axcrypt.net/"),
        ],

        "📊 Benchmark & Tests": [
            ("⚡ UserBenchmark", "https://www.userbenchmark.com/"),
            ("📊 3DMark", "https://benchmarks.ul.com/3dmark"),
            ("💻 PCMark", "https://benchmarks.ul.com/pcmark10"),
            ("🔍 Geekbench", "https://www.geekbench.com/"),
            ("⚡ Cinebench", "https://www.maxon.net/en/cinebench"),
            ("📈 PassMark", "https://www.passmark.com/"),
            ("💾 CrystalDiskMark", "https://crystalmark.info/en/software/crystaldiskmark/"),
            ("📊 AS SSD Bench", "https://www.alex-is.de/"),
            ("⚡ ATTO Disk Bench", "https://www.atto.com/disk-benchmark/"),
            ("🔍 HD Tune", "https://www.hdtune.com/"),
            ("📈 Unigine Heaven", "https://benchmark.unigine.com/heaven"),
            ("💻 Unigine Valley", "https://benchmark.unigine.com/valley"),
            ("📊 Unigine Superpos.", "https://benchmark.unigine.com/superposition"),
            ("⚡ FurMark", "https://geeks3d.com/furmark/"),
            ("🔍 Prime95", "https://www.mersenne.org/download/"),
            ("📈 AIDA64", "https://www.aida64.com/"),
            ("💾 MemTest86", "https://www.memtest86.com/"),
            ("📊 MemTest64", "https://www.techpowerup.com/memtest64/"),
            ("⚡ OCCT", "https://www.ocbase.com/"),
            ("🔍 Intel Burn Test", "https://www.techspot.com/downloads/4965-intel-burn-test.html"),
            ("📈 LinX", "https://www.techpowerup.com/download/linx/"),
            ("💻 Y-Cruncher", "http://www.numberworld.org/y-cruncher/"),
            ("📊 Blender Bench", "https://opendata.blender.org/"),
            ("⚡ V-Ray Bench", "https://www.chaos.com/vray/benchmark"),
            ("🔍 Basemark GPU", "https://www.basemark.com/products/basemark-gpu/"),
            ("📈 GFXBench", "https://gfxbench.com/"),
            ("💾 ADATA SSD Toolbox", "https://www.adata.com/us/ss/software-5/"),
            ("📦 Samsung Magician", "https://www.samsung.com/semiconductor/minisite/ssd/product/consumer/magician/"),
            ("⚡ WD Dashboard", "https://support.wdc.com/downloads.aspx"),
            ("🔍 Crucial SE", "https://www.crucial.com/support/storage-executive"),
            ("📈 NovaBench", "https://novabench.com/"),
            ("💻 CPU Monkey", "https://www.cpu-monkey.com/"),
            ("📊 GPU Check", "https://www.gpucheck.com/"),
            ("⚡ CPU-World", "http://www.cpu-world.com/"),
            ("🔍 TechPowerUp", "https://www.techpowerup.com/"),
            ("⚡ PowerToys", "https://github.com/microsoft/PowerToys/releases"),
            ("🔍 Everything", "https://www.voidtools.com/"),
            ("👁️ QuickLook", "https://github.com/QL-Win/QuickLook/releases"),
            ("📸 ShareX", "https://getsharex.com/"),
            ("🎯 Greenshot", "https://getgreenshot.org/"),
            ("📷 Lightshot", "https://app.prntscr.com/"),
            ("📦 7-Zip", "https://www.7-zip.org/"),
            ("🗜️ WinRAR", "https://www.win-rar.com/"),
            ("📦 PeaZip", "https://peazip.github.io/"),
            ("🗜️ Bandizip", "https://www.bandisoft.com/bandizip/"),
            ("📝 Notepad++", "https://notepad-plus-plus.org/"),
            ("⚡ Sublime Text", "https://www.sublimetext.com/"),
            ("💻 VS Code", "https://code.visualstudio.com/"),
            ("📝 Atom", "https://atom.io/"),
            ("✍️ Typora", "https://typora.io/"),
            ("⚡ AutoHotkey", "https://www.autohotkey.com/"),
            ("🎨 Rainmeter", "https://www.rainmeter.net/"),
            ("🔧 WinAutomation", "https://www.winautomation.com/"),
            ("📁 Total Commander", "https://www.ghisler.com/"),
            ("🗂️ FreeCommander", "https://freecommander.com/"),
            ("📂 XYplorer", "https://www.xyplorer.com/"),
            ("🗃️ Directory Opus", "https://www.gpsoft.com.au/"),
            ("🖱️ X-Mouse Button", "https://www.highrez.co.uk/downloads/XMouseButtonControl.htm"),
            ("⌨️ SharpKeys", "https://github.com/randyrants/sharpkeys/releases"),
            ("🎯 WinDirStat", "https://windirstat.net/"),
            ("📊 SpaceSniffer", "http://www.uderzo.it/main_products/space_sniffer/"),
            ("🔍 Agent Ransack", "https://www.mythicsoft.com/agentransack/"),
            ("🗂️ DropIt", "http://www.dropitproject.com/"),
            ("⏰ f.lux", "https://justgetflux.com/"),
            ("💡 Clover", "http://en.ejie.me/"),
            ("🚀 Launchy", "https://www.launchy.net/"),
            ("⚡ Wox", "http://www.wox.one/"),
            ("🎯 Keypirinha", "https://keypirinha.com/"),
            ("📋 Ditto", "https://ditto-cp.sourceforge.io/"),
            ("📝 ClipClip", "https://clipclip.com/"),
            ("⚡ CopyQ", "https://hluk.github.io/CopyQ/"),
            ("🪟 FancyZones", "https://learn.microsoft.com/windows/powertoys/fancyzones"),
            ("📐 AquaSnap", "https://www.nurgo-software.com/products/aquasnap"),
            ("🎯 DisplayFusion", "https://www.displayfusion.com/"),
            ("🎬 VLC Media Player", "https://www.videolan.org/vlc/"),
            ("▶️ MPC-HC", "https://mpc-hc.org/"),
            ("🎥 PotPlayer", "https://potplayer.daum.net/"),
            ("📺 Kodi", "https://kodi.tv/"),
            ("🎞️ MPV", "https://mpv.io/"),
            ("🎬 OBS Studio", "https://obsproject.com/"),
            ("📹 XSplit", "https://www.xsplit.com/"),
            ("🎥 vMix", "https://www.vmix.com/"),
            ("✂️ DaVinci Resolve", "https://www.blackmagicdesign.com/products/davinciresolve"),
            ("🎞️ Kdenlive", "https://kdenlive.org/"),
            ("📽️ OpenShot", "https://www.openshot.org/"),
            ("🎬 Shotcut", "https://www.shotcut.org/"),
            ("📹 HitFilm Express", "https://fxhome.com/hitfilm-express"),
            ("🎨 Blender", "https://www.blender.org/"),
            ("🏗️ SketchUp", "https://www.sketchup.com/"),
            ("📐 FreeCAD", "https://www.freecadweb.org/"),
            ("🎯 Meshmixer", "https://www.meshmixer.com/"),
            ("🎨 Inkscape", "https://inkscape.org/"),
            ("🖌️ Krita", "https://krita.org/"),
            ("🎨 GIMP", "https://www.gimp.org/"),
            ("🖼️ Paint.NET", "https://www.getpaint.net/"),
            ("📐 Figma", "https://www.figma.com/downloads/"),
            ("🎯 Canva", "https://www.canva.com/"),
            ("🎵 Audacity", "https://www.audacityteam.org/"),
            ("🎼 Reaper", "https://www.reaper.fm/"),
            ("🎹 FL Studio", "https://www.image-line.com/fl-studio/"),
            ("🎧 Ableton Live", "https://www.ableton.com/live/"),
            ("🎚️ Ardour", "https://ardour.org/"),
            ("🎵 Ocenaudio", "https://www.ocenaudio.com/"),
            ("🎧 VirtualDJ", "https://www.virtualdj.com/"),
            ("🎛️ Traktor", "https://www.native-instruments.com/traktor/"),
            ("🎵 Serato DJ", "https://serato.com/"),
            ("🎚️ Mixxx", "https://www.mixxx.org/"),
            ("🔄 HandBrake", "https://handbrake.fr/"),
            ("⚡ FFmpeg", "https://ffmpeg.org/"),
            ("🎬 Format Factory", "http://www.pcfreetime.com/formatfactory/"),
            ("📹 MediaCoder", "https://www.mediacoderhq.com/"),
            ("🎞️ MKVToolNix", "https://mkvtoolnix.download/"),
            ("📡 Streamlabs OBS", "https://streamlabs.com/"),
            ("🎥 Restream", "https://restream.io/"),
            ("📹 vMix", "https://www.vmix.com/"),
            ("📷 Darktable", "https://www.darktable.org/"),
            ("🖼️ RawTherapee", "https://www.rawtherapee.com/"),
            ("📸 digiKam", "https://www.digikam.org/"),
            ("🎨 Photopea", "https://www.photopea.com/"),
            ("🎵 MusicBee", "https://getmusicbee.com/"),
            ("📻 Spotify", "https://www.spotify.com/download/"),
            ("🎼 foobar2000", "https://www.foobar2000.org/"),
            ("📦 LibreOffice", "https://www.libreoffice.org/"),
            ("📄 OpenOffice", "https://www.openoffice.org/"),
            ("☁️ Google Workspace", "https://workspace.google.com/"),
            ("📊 OnlyOffice", "https://www.onlyoffice.com/"),
            ("📝 WPS Office", "https://www.wps.com/"),
            ("📓 Notion", "https://www.notion.so/"),
            ("🗒️ Obsidian", "https://obsidian.md/"),
            ("📔 OneNote", "https://www.onenote.com/"),
            ("📝 Evernote", "https://evernote.com/"),
            ("🗂️ Joplin", "https://joplinapp.org/"),
            ("✍️ Typora", "https://typora.io/"),
            ("📓 Logseq", "https://logseq.com/"),
            ("✅ Todoist", "https://todoist.com/"),
            ("📋 TickTick", "https://ticktick.com/"),
            ("✔️ Any.do", "https://www.any.do/"),
            ("📝 Microsoft To Do", "https://to-do.microsoft.com/"),
            ("🎯 Trello", "https://trello.com/"),
            ("📊 Asana", "https://asana.com/"),
            ("🗂️ Monday.com", "https://monday.com/"),
            ("⏱️ Toggl Track", "https://toggl.com/track/"),
            ("⏰ RescueTime", "https://www.rescuetime.com/"),
            ("🕐 Clockify", "https://clockify.me/"),
            ("⏲️ Harvest", "https://www.getharvest.com/"),
            ("💬 Slack", "https://slack.com/downloads/"),
            ("👥 Microsoft Teams", "https://www.microsoft.com/teams/"),
            ("📹 Zoom", "https://zoom.us/download"),
            ("🎥 Google Meet", "https://meet.google.com/"),
            ("📞 Webex", "https://www.webex.com/downloads.html"),
            ("💬 Discord", "https://discord.com/download"),
            ("🗨️ Mattermost", "https://mattermost.com/"),
            ("🚀 Rocket.Chat", "https://rocket.chat/"),
            ("📄 PDF24", "https://tools.pdf24.org/"),
            ("📋 PDFtk", "https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/"),
            ("📝 PDF-XChange", "https://www.tracker-software.com/product/pdf-xchange-editor"),
            ("📄 Foxit Reader", "https://www.foxit.com/pdf-reader/"),
            ("📋 Sumatra PDF", "https://www.sumatrapdfreader.org/"),
            ("📅 Google Calendar", "https://calendar.google.com/"),
            ("📆 Outlook", "https://outlook.com/"),
            ("🗓️ Thunderbird", "https://www.thunderbird.net/"),
            ("🧠 XMind", "https://www.xmind.net/"),
            ("🗺️ FreeMind", "http://freemind.sourceforge.net/"),
            ("💭 MindMeister", "https://www.mindmeister.com/"),
            ("💻 VS Code", "https://code.visualstudio.com/"),
            ("⚡ Sublime Text", "https://www.sublimetext.com/"),
            ("🎯 Atom", "https://atom.io/"),
            ("📝 Notepad++", "https://notepad-plus-plus.org/"),
            ("🔧 WebStorm", "https://www.jetbrains.com/webstorm/"),
            ("💼 PhpStorm", "https://www.jetbrains.com/phpstorm/"),
            ("🎨 PyCharm", "https://www.jetbrains.com/pycharm/"),
            ("☕ IntelliJ IDEA", "https://www.jetbrains.com/idea/"),
            ("🐙 GitHub Desktop", "https://desktop.github.com/"),
            ("🦊 GitKraken", "https://www.gitkraken.com/"),
            ("🌿 SourceTree", "https://www.sourcetreeapp.com/"),
            ("🔧 TortoiseGit", "https://tortoisegit.org/"),
            ("📦 XAMPP", "https://www.apachefriends.org/"),
            ("⚡ WAMP", "https://www.wampserver.com/"),
            ("🎯 Laragon", "https://laragon.org/"),
            ("💼 MAMP", "https://www.mamp.info/"),
            ("🐬 MySQL Workbench", "https://www.mysql.com/products/workbench/"),
            ("🐘 pgAdmin", "https://www.pgadmin.org/"),
            ("📊 DBeaver", "https://dbeaver.io/"),
            ("💾 HeidiSQL", "https://www.heidisql.com/"),
            ("📡 Postman", "https://www.postman.com/downloads/"),
            ("⚡ Insomnia", "https://insomnia.rest/"),
            ("🔧 Hoppscotch", "https://hoppscotch.io/"),
            ("📋 Thunder Client", "https://www.thunderclient.com/"),
            ("🐳 Docker Desktop", "https://www.docker.com/products/docker-desktop"),
            ("☸️ Kubernetes", "https://kubernetes.io/"),
            ("📦 Podman", "https://podman.io/"),
            ("💻 Windows Terminal", "https://apps.microsoft.com/detail/9N0DX20HK701"),
            ("⚡ Cmder", "https://cmder.app/"),
            ("🔧 ConEmu", "https://conemu.github.io/"),
            ("🎯 Hyper", "https://hyper.is/"),
            ("📁 FileZilla", "https://filezilla-project.org/"),
            ("🌐 WinSCP", "https://winscp.net/"),
            ("📦 Cyberduck", "https://cyberduck.io/"),
            ("🟢 Node.js", "https://nodejs.org/"),
            ("📦 npm", "https://www.npmjs.com/"),
            ("⚡ Yarn", "https://yarnpkg.com/"),
            ("🎯 pnpm", "https://pnpm.io/"),
            ("🐍 Python", "https://www.python.org/downloads/"),
            ("📦 Anaconda", "https://www.anaconda.com/products/distribution"),
            ("🎯 PyPI", "https://pypi.org/"),
            ("📚 DevDocs", "https://devdocs.io/"),
            ("💡 MDN Web Docs", "https://developer.mozilla.org/"),
            ("📖 W3Schools", "https://www.w3schools.com/"),
            ("🔍 Stack Overflow", "https://stackoverflow.com/"),
            ("💻 TeamViewer", "https://www.teamviewer.com/"),
            ("🖥️ AnyDesk", "https://anydesk.com/"),
            ("🌐 Chrome Remote", "https://remotedesktop.google.com/"),
            ("⚡ RustDesk", "https://rustdesk.com/"),
            ("🔧 TightVNC", "https://www.tightvnc.com/"),
            ("💼 UltraVNC", "https://uvnc.com/"),
            ("🎯 RealVNC", "https://www.realvnc.com/"),
            ("📡 Ammyy Admin", "https://www.ammyy.com/"),
            ("🌐 Splashtop", "https://www.splashtop.com/"),
            ("⚡ Parsec", "https://parsec.app/"),
            ("🔧 Moonlight", "https://moonlight-stream.org/"),
            ("💻 Remmina", "https://remmina.org/"),
            ("🖥️ NoMachine", "https://www.nomachine.com/"),
            ("📦 Supremo", "https://www.supremocontrol.com/"),
        ],

        "🔧 Drivers": [
            ("🔧 Snappy Driver", "https://www.snappy-driver-installer.org/"),
            ("⚡ Driver Booster", "https://www.iobit.com/driver-booster.php"),
            ("💻 Driver Easy", "https://www.drivereasy.com/"),
            ("🎯 DriverPack", "https://drp.su/"),
            ("🔍 Driver Genius", "https://www.driver-soft.com/"),
            ("📦 NVIDIA Drivers", "https://www.nvidia.com/download/index.aspx"),
            ("🔴 AMD Drivers", "https://www.amd.com/support"),
            ("🎯 Intel Drivers", "https://www.intel.com/content/www/us/en/download-center/home.html"),
            ("💻 Dell Drivers", "https://www.dell.com/support/home/"),
            ("🖥️ HP Drivers", "https://support.hp.com/drivers"),
            ("📱 Lenovo Drivers", "https://support.lenovo.com/solutions/ht003029"),
            ("🎮 ASUS Drivers", "https://www.asus.com/support/download-center/"),
            ("⚡ MSI Drivers", "https://www.msi.com/support/download"),
            ("🔧 Realtek Drivers", "https://www.realtek.com/downloads/"),
        ],

        "📚 Documentation": [
            ("📚 Microsoft Docs", "https://learn.microsoft.com/"),
            ("💻 Windows Tips", "https://support.microsoft.com/windows"),
            ("🔧 Sysinternals", "https://learn.microsoft.com/sysinternals/"),
            ("📖 SS64 CMD", "https://ss64.com/nt/"),
            ("⚡ PowerShell Docs", "https://learn.microsoft.com/powershell/"),
            ("🌐 TechNet", "https://technet.microsoft.com/"),
            ("📚 How-To Geek", "https://www.howtogeek.com/"),
            ("🔍 Stack Overflow", "https://stackoverflow.com/"),
            ("📖 Reddit r/techsupport", "https://www.reddit.com/r/techsupport/"),
            ("💻 Bleeping Computer", "https://www.bleepingcomputer.com/"),
            ("🔧 Ninite", "https://ninite.com/"),
            ("📚 AlternativeTo", "https://alternativeto.net/"),
            ("💡 CNET Download", "https://download.cnet.com/"),
            ("🌐 PortableApps", "https://portableapps.com/"),
        ],
    }
